### ISSUE TITLE
Improve K-Means

### ISSUE THREAD

**Issue by bytesnake** [rust-ml/linfa#102]
In a recent PR (#97) multiple issues came up with the current KMeans implementation. We could improve it by:

 * [x] adding kmeans++ for centroid initialization
 * [x] adding incremental KMeans mode
 * [x] using a more stable centroid updating scheme

**Comment by YuhanLiin** [comment]
After thinking about the empty cluster (cluster collapse) problem for a bit, I think it's better to handle empty clusters more gracefully than just throwing an error. This is because empty clusters do occur with real-world datasets. I found a version of Kmeans [here](https://www.researchgate.net/publication/228414762_A_Modified_k-means_Algorithm_to_Avoid_Empty_Clusters) that avoids NaNs and most empty centroids by slightly modifying the averaging step, so we can use that. It changes the averaging step from `new_centroid = cluster_total / cluster_size` to `new_centroid = (cluster_total + old_centroid) / (cluster_size+1)`.

**Comment by YuhanLiin** [comment]
What does "adding API for cluster size" mean?

**Comment by bytesnake** [comment]
number of empty clusters, but that can't really happen anymore

**Comment by YuhanLiin** [comment]
You can query the cluster sizes in general so that functionality is already possible. There's no API for reporting empty clusters but with the current algorithm that should almost never happen on non-degenerate data, so we can close this issue.
