### ISSUE TITLE
Awesome-rust-mentors

### ISSUE THREAD

**Issue by stokhos** [rust-ml/linfa#111]
Hi @bytesnake @quietlychris 

I saw your project on awesome-rust-mentors, and I'd like to be a mentee.
I didn't find much information on this, so I don't know how this works.

A brief bio about myself:
I'm PhD candidate in economics, close to get a Master degree in Mathematics. Had some experience ML, in mainly in DL.

Best

**Comment by bytesnake** [comment]
Hey, awesome to hear about your interest in linfa! I think we should discuss the details in zulip and not here, but I'll just write some infos about the mentorship. Because of your background I'll assume that you already know what you want to implement or what you are interested in? If not take a look at the [Roadmap](https://github.com/rust-ml/linfa/issues/7) to get some inspirations. The role of a mentor is to enable you to achieve your goal and find your way around in the community. You are the first mentee I'll have so it's new for me as well :smile: here a short list how I think it can work smoothly:

 * find a topic. If you are more interested in the language details, I would propose Least-Angle-Regression, because it's super simply, but useful for feature selection
 * create a dummy PR with a TODO list, so that we have an avenue for the mentorship. List all items, also some more trivial like: read paper/learn something about ndarray/basic functionality/extended functionality/etc.
 * read the paper and probably auxililiary resources. For simple questions, just write me a message on zulip. We can also do a short 1-to-1 meeting if you wish.
 * I will give feedback on code and advise resources for learning
 * (optional) write a blog post about what you've learned/algorithm and we'll post it on the website

The timing is bad though, I'll be afk for a week until 07. April because of eastern. So you'll have plenty of time to decide on a topic.
