### ISSUE TITLE
Provide non-accelerated algorithms without LAPACK routines

### ISSUE THREAD

**Issue by bytesnake** [rust-ml/linfa#147]
The people at [rust-cv](https://github.com/rust-cv) looked recently at some clustering algorithms in linfa and one issue which came up are dependencies to the LAPACK routines. In some situations you want to avoid these, for example in an embedding context.

Take for example the gaussian mixture model: the current implementation utilizes a cholesky decomposition for faster inverse and determinant computation and speeds the LL computation up. We could provide a second implementation which gets activated when the corresponding feature flags are deactivated and only provide models with independent univariates gaussians.

**Comment by quietlychris** [comment]
I'd definitely be interested in this as well! Now that I know the how-to, it's less of an issue, but I've run into issues on multiple occasions during the initial compilation of `linfa` because of our LAPACK and/or blas dependencies. I think you said this, but just to re-terate: it think it would be best the default, no-feature-flags-enabled use of that algorithm called an un-optimized version--only when a `lapack` feature flag is called would the `#[cfg(feature = "lapack")]` -marked version show up.

**Comment by vadixidav** [comment]
> 
> 
> I'd definitely be interested in this as well! Now that I know the how-to, it's less of an issue, but I've run into issues on multiple occasions during the initial compilation of `linfa` because of our LAPACK and/or blas dependencies. I think you said this, but just to re-terate: it think it would be best the default, no-feature-flags-enabled use of that algorithm called an un-optimized version--only when a `lapack` feature flag is called would the `#[cfg(feature = "lapack")]` -marked version show up.

This would be good. I think that the default behavior should not pull in blas/lapack if it can be helped, and if it does, there should be some pure-Rust alternative to avoid needing to bring in an external build system or downloading binaries (such as with intel-mkl). I also think it should be possible to bring in only the component of linfa that I need, which is just the GMM, without bringing in any other build dependencies that might expand the build. For one, that can make it more difficult to target `alloc` only, without using `std`, and then it can also increase the dependency chain in general (we already have 454 dependencies, so adding more does hurt a bit).

Since this isn't ready for us yet, and I really want to publish updated Rust CV crates soon, I think I will go with a simpler approach for the problem I am working on right now (basically chopping features in image frames up into equally-sized rectangles). If some assistance is needed on this, let me know, and I can probably lend a hand. I think that GMM will substantially improve the BoW matching performance over the naive approach.

**Comment by leo60228** [comment]
I have to admit that I don't really know linear algebra well enough to say if it's a viable alternative, but the `nalgebra` crate seems to have pure Rust implementations of most/all of the algorithms provided by LAPACK, as well as still having optional support for LAPACK.

**Comment by leo60228** [comment]
The `nshare` crate provides conversions between `nalgebra` and `ndarray` types, and was created for this purpose (an `ndarray-linalg` replacement without a hard dependency on LAPACK).

**Comment by bytesnake** [comment]
Using `nalgebra` introduces additional dependencies and compilation time, that should not be default choice. (we would also need LOBPCG support) We need to provide an efficient implementation of cholesky decomposition to solve the initial problem and eig/svd decompositions for all crates.

**Comment by vadixidav** [comment]
> Using `nalgebra` introduces additional dependencies and compilation time, that should not be default choice. (we would also need LOBPCG support) We need to provide an efficient implementation of cholesky decomposition to solve the initial problem and eig/svd decompositions for all crates.

`nalgebra` does provide cholesky decomp: https://docs.rs/nalgebra/0.29.0/nalgebra/base/struct.Matrix.html#method.cholesky. I cannot comment on its relative efficiency.

It also provides symmetric eigen and singular value decomposition.

Of course, if the build time issue is something you care about, I can understand. `nalgebra` will instantiate new implementations of everything for every new generic argument combination you choose, which REALLY slows down compilation for the consumer. Even if `ndarray` were to be replaced entirely, I think we could conclude that `nalgebra` would probably blow up compile times. However, Rust CV is relying exclusively on `nalgebra` for all linear algebra routines. The only time we use `ndarray` is actually for image manipulation routines, for which it seems to be better suited. I would also like to point out that there is a significant benefit to eliminating a dependency on these externally linked libraries, which can make it easier for people to "just start coding" on various platforms, instead of needing to worry about the installed BLAS & LAPACK libraries.

**Comment by YuhanLiin** [comment]
While I've never used `nalgebra`, I build the LAPACK libs statically and the build times for those take forever, so I'm in favour of introducing an alternative.

**Comment by bytesnake** [comment]
perhaps we can copy the implementations from `nalgebra` into a separate submodule called `decomps` and adapt them to use `ArrayBase`? I've never really worked with `nalgebra`, but found the type signatures quite noisy in the past

**Comment by YuhanLiin** [comment]
> I also think it should be possible to bring in only the component of linfa that I need, which is just the GMM, without bringing in any other build dependencies that might expand the build.
>
Does that mean we should split `linfa-clustering` into `linfa-gmm`, `linfa-kmeans`, and `linfa-dbscan`?

**Comment by YuhanLiin** [comment]
Regarding `nalgebra`, the instantiation of multiple implementations shouldn't be a problem because we'll only ever use dynamicly-sized matrices, so only a single generic argument combination will ever exist. Also, if the macros are disabled, the only dependencies in `nalgebra` that are not already part of `linfa-clustering`'s dependency tree are `num-rational` and `simba`, and `num-rational` is in the tree of another Linfa crate. The number of dependencies in `nalgebra` looks high due to its many optional features, but we only need a minimal build to use Cholesky. For these reasons, I believe that introducing `nalgebra` to Linfa will increase compile times, but not to a significant extent (if someone has experience that says otherwise, feel free to correct me). Adapting the Rust linalg routines from `nalgebra` for `ndarray` is essentially creating a version of `ndarray-linalg` that doesn't use LAPACK. Such a crate would be nice to have and easier to use for our usecase, but I'm not sure if it belongs in Linfa, so we could have it live somewhere else if we decide to not use `nalgebra`.

**Comment by bytesnake** [comment]
> Such a crate would be nice to have and easier to use for our usecase, but I'm not sure if it belongs in Linfa, so we could have it live somewhere else if we decide to not use nalgebra.

I think something like [matrixmultiply](https://github.com/bluss/matrixmultiply) for decompositions could contain implementations agnostic to the array backend

**Comment by YuhanLiin** [comment]
To encompass all LAPACK routines used by Linfa we'll need to include functions outside of decompositions as well. We also use functions like LOBPCG and eigenvalues, all of which rely on the LAPACK bindings from `linfa-linalg`.

**Comment by YuhanLiin** [comment]
Following are the LAPACK routines needed by each Linfa crate:

- [ ] `linfa-ica`: symmetric eigenvalues (eigh), SVD
- [ ] `linfa-reduction`: LOBPCG, eigh
- [ ] `linfa-clustering`: Cholesky, triangular solver
- [ ] `linfa-preprocessing`: Cholesky, SVD, inversion
- [ ] `linfa-pls`: SVD
- [ ] `linfa-linear`: Least Squares
- [ ] `linfa-elasticnet`: Inversion

The other crates should be already usable without LAPACK.

**Comment by YuhanLiin** [comment]
Closed by #207 🎉 🎉 🎉 🎉 🎉
