### ISSUE TITLE
Create Milestones or Projects and Associate with Future Releases

### ISSUE THREAD

**Issue by oojo12** [rust-ml/linfa#268]
This may be beneficial for organizing what work is done and tracking progress towards releases.

**Comment by oojo12** [comment]
For example, maybe 0.7.0 comes out with the addition of three more algorithms and 1.0.0 comes out once all Blas has been removed (if benchmarks show this is possible). Just some food for thought. I think it may make it easier to get community engagement.

**Comment by YuhanLiin** [comment]
We sort of have this with #7. I think this would be more useful if this project had more activity. Regarding when minor releases are made it really depends on what gets contributed. If enough significant changes have been added since last release we'll consider a new release, even if the changes aren't new algorithms. For 1.0.0 I'd only consider doing it after we finish both BLAS removal and Python FFI, if we decided to go that route. Both are very far down the line.
