### ISSUE TITLE
Add Profiling Hook to Criterion Benchmarks

### ISSUE THREAD

**Issue by oojo12** [rust-ml/linfa#272]
Per #254 and #262 we can get ahead of these issues and any optimization related ones by adding a profiling hook to our benchmarks. This is a feature that Criterion [supports](https://bheisler.github.io/criterion.rs/book/user_guide/profiling.html#implementing-in-process-profiling-hooks). Additionally, the profiler will only be run when running with the `--profile-time` flag. I also found this [post](https://www.jibbow.com/posts/criterion-flamegraphs/#:~:text=Criterion%20is%20a%20well-known%20and%20often-used%20benchmarking%20framework,to%20use%20a%20custom%20profiler%20while%20running%20benchmarks.) on how to do so with [pprof](https://crates.io/crates/pprof). Pprof also produces flamegraphs if that is of interest.

**Comment by YuhanLiin** [comment]
I've use `cargo-flamegraph` with `Criterion` before but the command was pretty involved. Using hooks makes this significantly less bothersome so I'm all for it. `pprof` is a good choice because it supports flamegraphs, which we should definitely generate. Note that the post you linked is a bit outdated, and the `pprof` docs actually have a simpler way of interfacing with Criterion and producing a flamegraph.

**Comment by oojo12** [comment]
sounds grand. I'll look into this later after trying to wrap up the target naming PR.

**Comment by oojo12** [comment]
Er actually, I'll go ahead and do this one and get back to the target naming PR later.
