### ISSUE TITLE
Rust implementation of DecisionTree::fit does not match results from sklearn

### ISSUE THREAD

**Issue by fgadaleta** [rust-ml/linfa#40]
Details in [PR-39](https://github.com/rust-ml/linfa/pull/39)

**Comment by paulkoerbitz** [comment]
@fgadaleta Thanks for reporting this issue. That looks indeed concern and the DecisionTree modules is solely lacking some tests on this level.

The DecisionTree module is a first stab - would you be interested in looking deeper into why it does not match the results from sklearn? We would certainly appreciate a contribution, especially if this leads to a better tested and more correct version of the DT.

**Comment by fgadaleta** [comment]
Sure thing. I am looking into it. 
I am also adding `linfa-ensemble` and random-forest that uses `linfa-trees` 
I will keep that feature under my fork until completion and then PR. Shall I add it as issue and assign it to myself to avoid double work?

**Comment by bytesnake** [comment]
I added your name to the algorithm roadmap #7, I think that ensemble learning would be a worthy addition. One problem though is that atm there is no standardized interface, because we're just getting to the point, where we have enough algorithms to think about a common trait, fitting different behaviours of algorithms. (like supervised/unsupervised, partial/entire learning etc.)  
Therefore a generic ensemble algorithm is a bit of a problem right now, but you could start with Random Forest for decision trees or perhaps invent such an interface :) If you have a first draft, just add a preliminary PR so that we can give feedback and support.

**Comment by fgadaleta** [comment]
Thanks. Yes the idea was to proceed with random-forest for decision trees and then add others later.
Do I continue committing to my fork and PR or will I get writing permissions to the repo?

**Comment by bytesnake** [comment]
You can commit to your fork, and when you think that you have a first draft open a PR. Any update on your fork will be reflected in the PR

**Comment by mossbanay** [comment]
I'm the author of the original implementation. Happy to look over the changes and help figure out why it's inconsistent with sklearn. It was a very scruffy first pass and definitely could do with some improvement.

**Comment by bytesnake** [comment]
this is an edge case, caused by the condition in https://github.com/rust-ml/linfa/blob/master/linfa-trees/src/decision_trees/algorithm.rs#L89

**Comment by mossbanay** [comment]
Okay actually we think it was related to equal values in the same feature not being treated correctly. We've added a test into the codebase for this case and it looks to be passing now :)

**Comment by bytesnake** [comment]
was fixed in https://github.com/rust-ml/linfa/pull/60
