### ISSUE TITLE
Confused about project layout

### ISSUE THREAD

**Issue by xd009642** [rust-ml/linfa#52]
Hopefully, just a quick query. So looking in the cargo.toml, most of the workspace members are added as dependencies for linfa, meaning they're pulled into the library at `src/lib.rs`, however only clustering publicly exposed making the other ones inclusion currently useless.

So from this I guess the plan is to publish each workspace member separately (which is nice). But also have a main crate called linfa that pulls everything in just for convenience?

If that is the case I'd consider making the project root a virtual workspace, adding a library project just called linfa in that and then pulling in the others as dependencies there. I've done that before in some personal projects and it worked well.

Some form of tidy-up and some people making sample projects using it to get a feel for the ergonomics would be good before another release

**Comment by bytesnake** [comment]
I think there are two things we have to do before the `0.2` release. 
 * make all dependencies to the subcrates optional and introduce features for common groups (e.g. supervised/unsupervised, clustering/projection/source separation) which are pulling in the crates on wish
 * make serde optionally (or use miniserde)

We are currently trying to fill up the holes of the roadmap #7 and create a common interface for the training process #45. When all current open PRs are merged the next minor release is due. The release was delayed because atm there is no usable interface. Once we have that, a minor version is published for each new algorithm. Hope this helps!

**Comment by xd009642** [comment]
Yeah that clears things up, I'll close this :+1: .

Also one consideration, if there's just a traits crate like `linfa-traits` then other ML crates could bring in just the traits to create linfa compatible interfaces to their models. Could make interacting with different things across the ML ecosystem nicer including things like more generic ensemble methods :smile:

**Comment by bytesnake** [comment]
sounds like a good idea :+1: once the traits prove to be useful and are used within the `linfa` crate, we could promote them in the machine learning group

**Comment by bytesnake** [comment]
#55
