### ISSUE TITLE
save model

### ISSUE THREAD

**Issue by julama** [rust-ml/linfa#67]
hey, I'm new to linfa and couldn't find methods to save and load trained models.
Any ideas how this could be done? Thanks!

**Comment by bytesnake** [comment]
there is no API for this yet, but it can be achieved with some special code. What algorithm do you want to export and load?

**Comment by julama** [comment]
I want to export and load kmeans and dbscan. Later eventually also svm

**Comment by bytesnake** [comment]
I just pushed a new commit with which you can enable serde support for almost all algorithms. In order to use SVM with serde support, add this to your `Cargo.toml`:
```rust
linfa-svm = { git = "https://github.com/rust-ml/linfa.git", features = ["serde"], default-features = false }
```
Once the a new version is published on `crates.io` I will notify you here. By the way, there is no "sane" support for prediction in DBSCAN. (see for example [here](https://github.com/rust-ml/linfa.git)), so you have to predict your clusters each time anew.

**Comment by bytesnake** [comment]
oh and if you don't know about `serde`, two popular serialization backends are
 * [bincode](https://github.com/servo/bincode) for binary encoding
 * [serde-json](https://github.com/serde-rs/json) for readable JSON encoding
you have to add them before serialization into a string/byte buffer, but there are plenty of examples on the websites

**Comment by ccmvn** [comment]
Are there already new features for it or do you still recommend serde to load and save? @bytesnake
