### ISSUE TITLE
DBSCAN does not count border points

### ISSUE THREAD

**Issue by YuhanLiin** [rust-ml/linfa#99]
The DBSCAN implementation in linfa-clustering only includes core points with minPts neighbours. Border points (points with less than minPts neighbours) connected to core points are counted as noise, which is different behaviour from how DBSCAN is typically described. Is this behaviour intentional or a bug?

**Comment by Sauro98** [comment]
Hi, nice find, I don't believe that they should be counted as noise. In theory, border points could belong to more than one cluster but, since we can only return a single cluster membership value for each point, I believe that we should arbitrarily choose a single cluster for each border point like the approximate dbscan implementation does. Would you like to open a PR fixing this? This should be fixable with like three lines of code I think 👍🏻

**Comment by YuhanLiin** [comment]
Might also be an issue with appx_dbscan as well, since those tests are failing after my fix.

**Comment by bytesnake** [comment]
resolved in #100
